name: Sanity Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      
      # - name: Compile on arm Mac
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     make mac-arm

      - name: Compile on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          make ubuntu
        
      # - name: Compile on MacOS
      #   if: matrix.os == 'macos-14'
      #   run: | 
      #     make mac

      - name: Install system dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-dev python3-pip build-essential libopenblas-dev liblapack-dev gfortran
          python3 -m venv venv
          source venv/bin/activate
          pip3 install matplotlib numpy psutil

      - name: Install system dependencies on MacOS
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-14'
        run: |
          brew install openblas lapack
          python3 -m venv venv
          source venv/bin/activate
          pip3 install matplotlib numpy psutil

      - name: Test
        run: |
          make test

      - name: Test Metamorph and DTest Integration
        run: |
          scripts/./generate_tests_with_metamorph.sh Benchmarks/CMTL/HKDF.dfy 80
